# Generated by Django 3.2.4 on 2021-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
    ]
