# Generated by Django 3.2.4 on 2021-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_place_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
