# Generated by Django 3.2.4 on 2021-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_alter_place_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
