# Generated by Django 3.2.4 on 2021-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_remove_place_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visited',
            field=models.BooleanField(default=1),
        ),
    ]
