# Generated by Django 3.2.4 on 2021-06-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_alter_place_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='visited',
        ),
    ]
