# Generated by Django 3.2.4 on 2021-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
