# Generated by Django 3.2.4 on 2021-06-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_rename_type_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='visited',
        ),
    ]
