# Generated by Django 3.2.4 on 2021-06-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0010_remove_place_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
    ]
