# Generated by Django 3.2.4 on 2021-06-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0013_place_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
