# Generated by Django 3.2.4 on 2021-06-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0014_place_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='choice',
        ),
        migrations.AddField(
            model_name='place',
            name='choice_dropdown',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('Maybe', 'Maybe')], default='no', max_length=10),
        ),
    ]
